Repository python-discord/forms-frontend, pull requests merged in 2020-12, with the labels that each got.

#28 Create review-policy.yml
  .github/review-policy.yml
Labels: needs 1 approval

#44 Replace broken webpack mode config with NODE_ENV
  webpack.config.js
Labels: area: CI, area: dependencies, needs 1 approval

#34 Fix Environment Modifying Scripts on Windows
  package.json
  yarn.lock
Labels: area: dependencies

#57 Add required field to question interface
  src/api/question.ts
Labels: area: back-end

#60 Adds Dotenv to Project
  .gitignore
  package.json
  webpack.config.js
  yarn.lock
Labels: area: dependencies, type: feature
