Repository python-discord/forms-frontend, pull requests merged in 2021-02, with the labels that each got.

#107 Housekeeping
  .eslintrc.json
  CONTRIBUTING.md
  README.md
  package.json
  public/apple-touch-icon-precomposed.png
  public/apple-touch-icon.png
  public/branding/browserconfig.xml
  public/branding/logo192.png
  public/branding/logo256.png
  public/branding/logo512.png
  public/branding/mstile-144x144.png
  public/branding/mstile-150x150.png
  public/branding/mstile-310x150.png
  public/branding/mstile-310x310.png
  public/branding/mstile-70x70.png
  public/branding/safari-pinned-tab.svg
  public/index.html
  public/manifest.json
  renovate.json
  src/logo.svg
  src/pages/LandingPage.tsx
  src/setupTests.ts
  src/tests/components/FormListing.test.tsx
Labels: priority: low, type: enhancement

#129 Cleanup depends
  .github/workflows/create_sentry_release.yml
  .github/workflows/test_and_lint.yml
  package.json
  src/index.tsx
  webpack.config.js
  yarn.lock
Labels: area: CI, area: dependencies, type: enhancement

#133 Add ESLint formatter for GHA annotations and add it to workflow
  .github/workflows/test_and_lint.yml
  annotations_formatter.js
  package.json
Labels: area: CI
